#!/bin/bash

###########################
#(C) Will Cunningham 2016 #
#         DK Lab          #
# Northeastern University #
###########################

./bin/Evolution_$HOSTNAME --nodes 25 --sweeps 100 --beta 0.5 --epsilon 0.21 --j -10.0 --print -x 10 --spinflips 10
