#!/bin/bash

###########################
#(C) Will Cunningham 2016 #
#         DK Lab          #
# Northeastern University #
###########################

./bin/Evolution_krioukov_gpu --nodes 10 --sweeps 10 --beta 0 --epsilon 0.21 
