#!/bin/bash

###########################
# Lisa Glaser 2020        #
###########################

# this will run a little example with 40 elements and spincoupling -1 at beta=1.5
# explanations of the parameters can be surmised from causet.cpp

./bin/Evolution_$HOSTNAME --nodes 40 --sweeps 50000 --beta 1.5 --epsilon 0.21 --j -1 --print -x 40 -i random --spinflips 40 -c -x
